name: Deploy to Server

on:
  push:
    tags:
      -  "dev-*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.USR_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/ibrahimfattah/hisab-cal/backend:latest
            ghcr.io/ibrahimfattah/hisab-cal/backend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/ibrahimfattah/hisab-cal/backend:latest
          cache-to: type=inline
          
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          build-args: |
                NEXT_PUBLIC_API_URL=${{ secrets.SERVER_API_URL }}
          tags: |
            ghcr.io/ibrahimfattah/hisab-cal/frontend:latest
            ghcr.io/ibrahimfattah/hisab-cal/frontend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/ibrahimfattah/hisab-cal/frontend:latest
          cache-to: type=inline

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to app directory
            cd /root/hisabcal || exit 1
            # pruning
            docker container prune  -f
            docker image prune -a -f
            # docker system prune -a -f
            
            docker stop hisabcal-backend || true
            docker rm hisabcal-backend  || true
            
            docker stop hisabcal-frontend  || true
            docker rm hisabcal-frontend || true           
            
            echo "Deploying to dev environment ..."
            docker login ghcr.io -u ${{ github.actor }} --password "${{ secrets.USR_TOKEN }}"
            
            # Pull latest Docker images
            docker pull ghcr.io/ibrahimfattah/hisab-cal/backend:latest
            docker pull ghcr.io/ibrahimfattah/hisab-cal/frontend:latest

            docker compose down 
            docker compose up -d 

    
